-- ============================================
-- SCRIPT SIMPLES PARA CORRIGIR A TABELA LEADERS
-- ============================================
-- Execute este script no SQL Editor do Supabase
-- ============================================

-- Verificar a estrutura atual da tabela
SELECT 
    column_name, 
    data_type, 
    is_nullable 
FROM information_schema.columns 
WHERE table_name = 'leaders' 
ORDER BY ordinal_position;

-- Se a tabela não existir, criar ela
CREATE TABLE IF NOT EXISTS leaders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT NOT NULL,
    image TEXT NOT NULL,
    shortdescription TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Habilitar RLS
ALTER TABLE leaders ENABLE ROW LEVEL SECURITY;

-- Remover políticas existentes para evitar conflitos
DROP POLICY IF EXISTS "Acesso público para visualizar líderes" ON leaders;
DROP POLICY IF EXISTS "Permissão para inserir líderes" ON leaders;
DROP POLICY IF EXISTS "Permissão para atualizar líderes" ON leaders;
DROP POLICY IF EXISTS "Permissão para excluir líderes" ON leaders;

-- Criar políticas
CREATE POLICY "Acesso público para visualizar líderes" ON leaders
    FOR SELECT USING (true);

CREATE POLICY "Permissão para inserir líderes" ON leaders
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Permissão para atualizar líderes" ON leaders
    FOR UPDATE USING (true);

CREATE POLICY "Permissão para excluir líderes" ON leaders
    FOR DELETE USING (true);
