[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# ============================================
# VARIÁVEIS DE AMBIENTE NECESSÁRIAS
# ============================================
# Configure estas variáveis no Netlify Dashboard:
# Site Settings → Environment Variables
#
# VITE_SUPABASE_URL = "https://seu-projeto.supabase.co"
# VITE_SUPABASE_ANON_KEY = "sua-chave-anonima-aqui"
#
# ⚠️ IMPORTANTE: Use apenas a chave anônima (anon key)
# Nunca use a service_role key no frontend!
# 
# 📖 Veja DEPLOY-NETLIFY.md para instruções completas 