-- Criar tabela para tipos de culto
CREATE TABLE IF NOT EXISTS service_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    default_time TEXT NOT NULL,
    order_index INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Criar tabela para as escalas
CREATE TABLE IF NOT EXISTS schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_type_id BIGINT REFERENCES service_types(id) ON DELETE CASCADE NOT NULL,
    date TEXT NOT NULL,
    preacher TEXT,
    worship TEXT,
    reception TEXT,
    opening TEXT,
    sabbath_school TEXT,
    deacons TEXT,
    platform TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Habilitar RLS (Row Level Security)
ALTER TABLE service_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedules ENABLE ROW LEVEL SECURITY;

-- Criar políticas para permissão de leitura pública
CREATE POLICY "Acesso público para leitura de tipos de culto" 
ON service_types FOR SELECT USING (true);

CREATE POLICY "Acesso público para leitura de escalas" 
ON schedules FOR SELECT USING (true);

-- Criar políticas para permissão de escrita (apenas para testes)
-- Em produção, essas políticas seriam restritas a usuários autenticados ou admin
CREATE POLICY "Permissão para inserir tipos de culto" 
ON service_types FOR INSERT WITH CHECK (true);

CREATE POLICY "Permissão para atualizar tipos de culto" 
ON service_types FOR UPDATE USING (true);

CREATE POLICY "Permissão para excluir tipos de culto" 
ON service_types FOR DELETE USING (true);

CREATE POLICY "Permissão para inserir escalas" 
ON schedules FOR INSERT WITH CHECK (true);

CREATE POLICY "Permissão para atualizar escalas" 
ON schedules FOR UPDATE USING (true);

CREATE POLICY "Permissão para excluir escalas" 
ON schedules FOR DELETE USING (true);

-- Inserir tipos de culto padrão
INSERT INTO service_types (name, default_time, order_index) 
VALUES 
('Culto de Domingo', '19h', 1),
('Culto de Quarta', '19h30', 2),
('Culto de Sábado', '9h (Escola Sabatina) e 11h (Culto Divino)', 3)
ON CONFLICT DO NOTHING; 