-- Criar a tabela de estudos bíblicos
CREATE TABLE IF NOT EXISTS bible_studies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    image TEXT NOT NULL,
    instructor TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Habilitar RLS (Row Level Security) para a tabela bible_studies
ALTER TABLE bible_studies ENABLE ROW LEVEL SECURITY;

-- Criar política para permitir leitura pública
CREATE POLICY "Acesso público para visualizar estudos" ON bible_studies
    FOR SELECT USING (true);

-- Criar política para permitir inserção por usuários anônimos (apenas para testes)
-- Em produção, seria restrito a usuários autenticados ou serviço
CREATE POLICY "Permissão para inserir estudos" ON bible_studies
    FOR INSERT WITH CHECK (true);

-- Criar política para permitir atualização por usuários anônimos (apenas para testes)
-- Em produção, seria restrito a usuários autenticados ou serviço
CREATE POLICY "Permissão para atualizar estudos" ON bible_studies
    FOR UPDATE USING (true);

-- Criar política para permitir exclusão por usuários anônimos (apenas para testes)
-- Em produção, seria restrito a usuários autenticados ou serviço
CREATE POLICY "Permissão para excluir estudos" ON bible_studies
    FOR DELETE USING (true);

-- Criar a tabela de lições
CREATE TABLE IF NOT EXISTS lessons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_id BIGINT REFERENCES bible_studies(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    order INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Habilitar RLS (Row Level Security) para a tabela lessons
ALTER TABLE lessons ENABLE ROW LEVEL SECURITY;

-- Criar política para permitir leitura pública
CREATE POLICY "Acesso público para visualizar lições" ON lessons
    FOR SELECT USING (true);

-- Criar política para permitir inserção por usuários anônimos (apenas para testes)
-- Em produção, seria restrito a usuários autenticados ou serviço
CREATE POLICY "Permissão para inserir lições" ON lessons
    FOR INSERT WITH CHECK (true);

-- Criar política para permitir atualização por usuários anônimos (apenas para testes)
-- Em produção, seria restrito a usuários autenticados ou serviço
CREATE POLICY "Permissão para atualizar lições" ON lessons
    FOR UPDATE USING (true);

-- Criar política para permitir exclusão por usuários anônimos (apenas para testes)
-- Em produção, seria restrito a usuários autenticados ou serviço
CREATE POLICY "Permissão para excluir lições" ON lessons
    FOR DELETE USING (true);

-- Verificar se o bucket já existe e criar se não existir
DO $$
BEGIN
    -- Criar o bucket para armazenar imagens de estudos bíblicos
    INSERT INTO storage.buckets (id, name, public)
    VALUES ('bible-studies', 'bible-studies', true)
    ON CONFLICT (id) DO NOTHING;
END
$$;

-- Criar política para acesso público às imagens no bucket
CREATE POLICY "Acesso público para visualizar imagens de estudos bíblicos" ON storage.objects
    FOR SELECT
    USING (bucket_id = 'bible-studies');

-- Criar política para upload de imagens (apenas para testes)
-- Em produção, seria restrito a usuários autenticados ou serviço
CREATE POLICY "Acesso para fazer upload de imagens de estudos bíblicos" ON storage.objects
    FOR INSERT
    WITH CHECK (bucket_id = 'bible-studies');

-- Criar política para atualizar imagens (apenas para testes)
-- Em produção, seria restrito a usuários autenticados ou serviço
CREATE POLICY "Acesso para atualizar imagens de estudos bíblicos" ON storage.objects
    FOR UPDATE
    USING (bucket_id = 'bible-studies');

-- Criar política para excluir imagens (apenas para testes)
-- Em produção, seria restrito a usuários autenticados ou serviço
CREATE POLICY "Acesso para remover imagens de estudos bíblicos" ON storage.objects
    FOR DELETE
    USING (bucket_id = 'bible-studies'); 